export const tabs =  ['Designs', 'Professional', 'Gradients', 'Cafes', 'Retailers','Customizable', 'Review'];

export const CustomizableData =[
    {
        id:1,
        image: '/Gallery/customizable/1f.png',
        back: '/Gallery/customizable/1b.png',
        title: 'Customizable',
        name: 'Influencer',
        description: 'Customize your own design',
    },
    {
        id:2,
        image: '/Gallery/customizable/2f.png',
        back: '/Gallery/customizable/2b.png',
        title: 'Customizable',
        name: 'Corporate Cuisine',
        description: 'Customize your own design',
    },
    {
        id:3,
        image: '/Gallery/customizable/3f.png',
        back: '/Gallery/customizable/3b.png',
        title: 'Customizable',
        name: 'Heart Memoji',
        description: 'Customize your own design',
    },
    {
        id:4,
        image: '/Gallery/customizable/4f.png',
        back: '/Gallery/customizable/4b.png',
        title: 'Customizable',
        name: 'BTS Memoji',
        description: 'Customize your own design',
    },
    // {
    //     id:5,
    //     image: '/Gallery/customizable/5f.png',
    //     title: 'Customizable',
    //     description: 'Customize your own design',
    // },
]

export const ProfessionData =[
    {
        id:1,
        image: '/Gallery/profession/1f.png',
        back: '/Gallery/profession/1b.png',
        title: 'Profession',
        name: 'Chic Canvas',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/2f.png',
        back: '/Gallery/profession/2b.png',
        title: 'Profession',
        name: 'Vogue Vista',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/3f.png',
        back: '/Gallery/profession/3b.png',
        title: 'Profession',
        name: 'Scientist',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/4f.png',
        back: '/Gallery/profession/4b.png',
        title: 'Profession',
        name: 'Style Sculpt',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/5f.png',
        back: '/Gallery/profession/5b.png',
        title: 'Profession',
        name: 'Designer',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/6f.png',
        back: '/Gallery/profession/6b.png',
        title: 'Profession',
        name: 'Advocate',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/7f.png',
        back: '/Gallery/profession/7b.png',
        title: 'Profession',
        name: 'Lawyer',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/8f.png',
        back: '/Gallery/profession/8b.png',
        title: 'Profession',
        name: 'Indian Navy',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/9f.png',
        back: '/Gallery/profession/9b.png',
        title: 'Profession',
        name: 'Indian Air Force',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/10f.png',
        back: '/Gallery/profession/10b.png',
        title: 'Profession',
        name: 'Indian Army',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/11f.png',
        back: '/Gallery/profession/11b.png',
        title: 'Profession',
        name: 'IPS',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/12f.png',
        back: '/Gallery/profession/12b.png',
        title: 'Profession',
        name: 'Singham',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/13f.png',
        back: '/Gallery/profession/13b.png',
        title: 'Profession',
        name: 'Sooryavanshi',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/14f.png',
        back: '/Gallery/profession/14b.png',
        title: 'Profession',
        name: 'Corporate',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/15f.png',
        back: '/Gallery/profession/15b.png',
        title: 'Profession',
        name: 'Doctor',
        description: 'Profession',
    },
    {
        id:1,
        image: '/Gallery/profession/16f.png',
        back: '/Gallery/profession/16b.png',
        title: 'Profession',
        name: 'Architect',
        description: 'Profession',
    },
    // {
    //     id:1,
    //     image: '/Gallery/profession/17f.png',
    //     title: 'Profession',
    //     description: 'Profession',
    // },
]

export const DesignData =[
    {
        id:1,
        image: '/Gallery/designs/1f.png',
        back: '/Gallery/designs/1b.png',
        title: 'Design',
        name: 'Blue Topaz',
        description: 'Design',
    },
    {
        id:1,
        image: '/Gallery/designs/2f.png',
        back: '/Gallery/designs/2b.png',
        title: 'Design',
        name: 'Sapphire', 
        description: 'Design',
    },
    {
        id:1,
        image: '/Gallery/designs/3f.png',
        back: '/Gallery/designs/3b.png',
        title: 'Design',
        name: 'Midnight Gilt',
        description: 'Design',
    },
    {
        id:1,
        image: '/Gallery/designs/4f.png',
        back: '/Gallery/designs/4b.png',
        title: 'Design',
        name: 'Cobalt Carat',
        description: 'Design',
    },
    {
        id:1,
        image: '/Gallery/designs/5f.png',
        back: '/Gallery/designs/5b.png',
        title: 'Design',
        name: 'Emerald',
        description: 'Design',
    },
    {
        id:1,
        image: '/Gallery/designs/6f.png',
        back: '/Gallery/designs/6b.png',
        title: 'Design',
        name: 'Black Jet',
        description: 'Design',
    },
    {
        id:1,
        image: '/Gallery/designs/7f.png',
        back: '/Gallery/designs/7b.png',
        title: 'Design',
        name: 'Zircon',
        description: 'Design',
    },
]

export const GradientData =[
    {
        id:1,
        image: '/Gallery/gradients/1f.png',
        back: '/Gallery/gradients/1b.png',
        title: 'Gradient',
        name: 'Magenta Sky',
        description: 'Gradient',
    },
    {
        id:1,
        image: '/Gallery/gradients/2f.png',
        back: '/Gallery/gradients/2b.png',
        title: 'Gradient',
        name: 'Blue Lagoon',
        description: 'Gradient',
    },
    {
        id:1,
        image: '/Gallery/gradients/3f.png',
        back: '/Gallery/gradients/3b.png',
        title: 'Gradient',
        name: 'Tequila Sunrise',
        description: 'Gradient',
    },
    {
        id:1,
        image: '/Gallery/gradients/4f.png',
        back: '/Gallery/gradients/4b.png',
        title: 'Gradient',
        name: 'French Martini',
        description: 'Gradient',
    },
]

export const RestroCafeData =[
    {
        id:1,
        image: '/Gallery/restro-cafe/1f.png',
        back: '/Gallery/restro-cafe/1b.png',
        title: 'Restro Cafe',
        name: 'Curry Canvas',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/2f.png',
        back: '/Gallery/restro-cafe/2b.png',
        title: 'Restro Cafe',
        name: 'Majestic Morsel',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/3f.png',
        back: '/Gallery/restro-cafe/3b.png',
        title: 'Restro Cafe',
        name: 'Tan Toast',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/4f.png',
        back: '/Gallery/restro-cafe/4b.png',
        title: 'Restro Cafe',
        name: 'Majestic Manor',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/5f.png',
        back: '/Gallery/restro-cafe/5b.png',
        title: 'Restro Cafe',
        name: 'Crust & Craft',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/6f.png',
        back: '/Gallery/restro-cafe/6b.png',
        title: 'Restro Cafe',
        name: 'Sunburst Brews',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/7f.png',
        back: '/Gallery/restro-cafe/7b.png',
        title: 'Restro Cafe',
        name: 'Grill Grove',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/8f.png',
        back: '/Gallery/restro-cafe/8b.png',
        title: 'Restro Cafe',
        name: 'Mocha Muse',
        description: 'Restro Cafe',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/9f.png',
        title: 'Restro Cafe',
        description: 'Restro Cafe',
    },
    
]

export const ReviewData=[
    {
        id:5,
        image: '/Gallery/customizable/5f.png',
        title: 'Customizable',
        description: 'Customize your own design',
    },
]

export const RetailerData =[
    {
        id:1,
        image: '/Gallery/retailers/1f.png',
        back: '/Gallery/retailers/1b.png',
        title: 'Retailer',
        name: 'Trend Trove',
        description: 'Retailer',
    },
    {
        id:1,
        image: '/Gallery/retailers/2f.png',
        back: '/Gallery/retailers/2b.png',
        title: 'Retailer',
        name: 'Pinnacle Pulse',
        description: 'Retailer',
    },
    {
        id:1,
        image: '/Gallery/retailers/3f.png',
        back: '/Gallery/retailers/3b.png',
        title: 'Retailer',
        name: 'Shop Spot',
        description: 'Retailer',
    },
    {
        id:1,
        image: '/Gallery/retailers/4f.png',
        back: '/Gallery/retailers/4b.png',
        title: 'Retailer',
        name: 'Luxe',
        description: 'Retailer',
    },
    {
        id:1,
        image: '/Gallery/retailers/5f.png',
        back: '/Gallery/retailers/5b.png',
        title: 'Retailer',
        name: 'Glam Grove',
        description: 'Retailer',
    },
    {
        id:1,
        image: '/Gallery/retailers/6f.png',
        back: '/Gallery/retailers/6b.png',
        title: 'Retailer',
        name: 'Salon',
        description: 'Retailer',
    },
    {
        id:1,
        image: '/Gallery/restro-cafe/9f.png',
        back: '/Gallery/restro-cafe/9b.png',
        title: 'Restro Cafe',
        name: 'Brew Haven',
        description: 'Restro Cafe',
    },
]